### ISSUE TITLE
Landmarks Move Despite Being Set as Non-Movable

### ISSUE THREAD

**Issue by aryanj2003** [mariojerez/RL-MultiAgent-PettingZoo#5] opened 2024-11-17 06:02 UTC
Description:
I encountered an issue where landmarks in the environment appear to move slightly, even though they are initialized as non-movable (landmark.movable = False). Despite setting their positions explicitly in the reset_world method and ensuring their velocities are zero, the positions seem to vary during resets or rendering. This behavior is unexpected as the landmarks are supposed to remain stationary.

Steps to Reproduce:

Modify the reset_world method to set fixed positions for landmarks:

for i, landmark in enumerate(world.landmarks):
    landmark.state.p_pos = np.array([i * 0.5, 0])
    landmark.state.p_vel = np.zeros(world.dim_p)
Add debug prints to track positions during reset_world and render.
Run the environment and observe that landmark positions change slightly after each reset.
What I Tried:

Ensured that landmark.movable is set to False.
Explicitly set landmark.state.p_vel = np.zeros(world.dim_p) to prevent movement.
Verified that landmark.state.p_pos is correctly initialized in reset_world.
Checked that no updates to landmark positions occur in world.step.
Observed Behavior:
Landmarks exhibit slight changes in position after each reset, despite being initialized with fixed positions. The positions remain consistent during rendering.

Expected Behavior:
Landmarks should maintain their fixed positions across resets and throughout the simulation since they are non-movable.

Request:
Please confirm if this is a bug or if there are additional steps required to ensure landmarks remain stationary. Let me know if further details are needed.

**Comment by mariojerez** [comment] 2024-11-18 06:57
This is a duplicate of issue #2

**Closed as not planned by mariojerez** 2024-11-18 06:57 UTC
